// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/runetale/runetale-handshake-server/domain/entity"
	"github.com/runetale/runetale-handshake-server/infura/interface"
	"github.com/runetale/runetale-handshake-server/infura/repository"
	"github.com/runetale/runetale-handshake-server/usecase/interactor"
	"github.com/runetale/runetale-handshake-server/utility"
)

// Injectors from wire.go:

// Interactor
func InitialNegotiationInteractor(cache *entity.PeerCache, logger *utility.Logger) infura.NegotiationInteractor {
	peerRepository := repository.NewPeerRepositoryImpl(cache, logger)
	negotiationInteractor := interactor.NewNegotiationInteractorImpl(peerRepository, logger)
	return negotiationInteractor
}

// wire.go:

var wireSet = wire.NewSet(interactor.WireSet, repository.WireSet)
